# Generated by Django 3.2.5 on 2021-07-02 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('player_one', models.CharField(max_length=64)),
                ('player_two', models.CharField(max_length=64)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_time', models.TimeField(auto_now_add=True)),
                ('square', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.game')),
            ],
        ),
    ]
