# Generated by Django 3.2.5 on 2021-07-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['move_time']},
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='tictactoe.game'),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('game', 'square')},
        ),
    ]
