# Generated by Django 3.2.5 on 2021-07-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_auto_20210702_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
