# Generated by Django 3.2.5 on 2021-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_auto_20210702_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.CharField(default='         ', max_length=9),
        ),
    ]
